#!/bin/sh

TZ=${TZ:-Europe/Moscow}
LOCALE=${LOCALE:-en_EN}
CRON_HINT_FILE=${CRON_HINT_FILE:-https://www.internic.net/domain/named.root}
CRON_HINT_TIME=${CRON_HINT_TIME:-0 1 1 * * *}

cp /usr/share/zoneinfo/${TZ} /etc/localtime

LANG=${LOCALE}.UTF-8
LANGUAGE=${LOCALE}.UTF-8
LC_ALL=${LOCALE}.UTF-8
MUSL_LOCPATH=/usr/share/i18n/locales/musl

export LANG
export LANGUAGE
export LC_ALL
export MUSL_LOCPATH

echo "${CRON_HINT_TIME} wget -O /etc/bind/named.root ${CRON_HINT_FILE}" >> /etc/crontabs/root && echo "#" >> /etc/crontabs/root
echo "nameserver 127.0.0.1" > /etc/resolv.conf

/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
