dnssec-policy "monthly" {
  keys {
    csk lifetime P30D algorithm ecdsap256sha256;
  };
};

dnssec-policy "standard" {
    keys {
        csk lifetime unlimited algorithm ecdsap256sha256;
    };
};

