logging {
    channel default_log { syslog daemon; severity info; print-severity yes; print-category yes; print-time yes; };
    channel errors_log { syslog daemon; severity warning; print-severity yes; print-category yes; print-time yes; };
    channel security_file {
        file "/var/log/named/security.log" versions 3 size 10m;
        severity dynamic;
        print-severity yes;
        print-category yes;
        print-time yes;
    };

    category default { default_log; };
    category config { default_log; };
    category security { errors_log; security_file; };
    category xfer-in { default_log; security_file; };
    category xfer-out { default_log; security_file; };
    category update { default_log; };
    category dnssec { default_log; };
    category queries { default_log; };
};
