logging {
    channel default_log { syslog daemon; severity info; print-severity yes; print-category yes; print-time yes; };
    channel errors_log { syslog daemon; severity warning; print-severity yes; print-category yes; print-time yes; };

    category default { default_log; };
    category config { default_log; };
    category security { errors_log; };
    category xfer-in { default_log; };
    category xfer-out { default_log; };
    category update { default_log; };
    category dnssec { default_log; };
};
