include "/etc/bind/acl.conf";
include "/etc/bind/option.conf";
include "/etc/bind/logging.conf";
include "/etc/bind/dnssec-policy.conf";
include "/etc/bind/controls.conf";
include "/etc/bind/rndc.key";

// Master zone with DNSSEC
//zone "example.com" {
//    type master;
//    file "/etc/bind/zones/dnssec/db.example.com";
//    allow-transfer { 192.168.1.11; };
//    notify explicit;
//    also-notify { 192.168.1.11; };
//    key-directory "/var/cache/bind/keys";
//    dnssec-policy monthly;
//    inline-signing yes;
//};

// Master zone without DNSSEC
//zone "example.net" {
//    type master;
//    file "/etc/bind/zones/master/db.example.net";
//    allow-transfer { 192.168.1.11; };
//    notify explicit;
//    also-notify { 192.168.1.11; };
//};

// Slave zone The zone file is created automatically after the first successful transfer.
//zone "example.org" {
//    type slave;
//    masters { 192.168.1.10; };
//    file "/etc/bind/zones/slave/db.example.org";
//};
