options {
    directory "/var/cache/bind";
    listen-on port 53 { any; };
    listen-on-v6 { any; };

    allow-query { any; };
    blackhole { blocked; };
    recursion no;

    // Security
    version "unknown";
    hostname "unknown";
    server-id "unknown";
};
